# kubectl apply -f https://bit.ly/echo-service

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ecsimsw@gmail.com #please change this/this is an optional, but recommended setting
    privateKeySecretRef:
      name: letsencrypt-prod # or you can use 'letsencrypt-staging' for test
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            podTemplate:
              metadata:
                annotations:
                  kuma.io/sidecar-injection: 'false'   # If ingress is running in Kuma/Kong Mesh, disable sidecar injection
                  sidecar.istio.io/inject: 'false'  # If using Istio, disable sidecar injection
            class: kong
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certmanager-ingress-sample
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # or you can use 'letsencrypt-staging' for test
spec:
  ingressClassName: kong
  tls:
    - secretName: test.ecsimsw.com # This secret will be created by cert-manager.
      hosts:
        - test.ecsimsw.com
  rules:
    - host: test.ecsimsw.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 80
