apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ip-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.52.20-192.168.52.30

# Node1 : 192.168.52.10
# Node2 : 192.168.52.11
# Node3 : 192.168.52.12
