version: '3'
services:
  gateway-nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./route-ecsimsw.conf:/etc/nginx/conf.d/route.conf
      - ./static/:/static
      - /etc/letsencrypt:/etc/letsencrypt
      - ~/dev/data/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"